config/routes.rb
Rails.application.routes.draw do

  resources :exams, only: [:index, :show] do
    get :start_exam, on: :member
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :candidates

  # You can have the root of your site routed with "root"
  root 'home#index'

  get 'secret' => 'home#secret'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'

  get '/profile', to: 'home#profile', as: :candidate_profile
  post '/test/:test_id/answer', to: 'exams#answer', as: :test_answer
  post '/test/:test_id/complete_test', to: 'exams#complete_test', as: :complete_test
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :question

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :other_exams_marks
  has_many :model_tests
  has_and_belongs_to_many :exams

end

app/models/exam.rb
class Exam < ActiveRecord::Base

  has_and_belongs_to_many :questions
  has_many :model_tests
  has_and_belongs_to_many :candidates


  def exam_given(candidate)
   model_tests.where(candidate_id:  candidate.id).first
  end
end

app/models/model_test.rb
class ModelTest < ActiveRecord::Base
  belongs_to :candidate
  belongs_to :exam
  has_many :model_test_answers
end

app/models/model_test_answer.rb
class ModelTestAnswer < ActiveRecord::Base
  belongs_to :model_test
end

app/models/other_exam.rb
class OtherExam < ActiveRecord::Base

  has_many :other_exams_marks

  def get_mark(candidate_id)
    exam_mark = self.other_exams_marks.where(candidate_id: candidate_id).first
    exam_mark.present? ? exam_mark.point : ''
  end
end

app/models/other_exams_mark.rb
class OtherExamsMark < ActiveRecord::Base

  belongs_to :candidate
  belongs_to :other_exam

end

app/models/question.rb
class Question < ActiveRecord::Base

  has_many :answers
  has_and_belongs_to_many :exams
  belongs_to :correct_answer, class_name: 'Answer', foreign_key: :correct_answer_id

  accepts_nested_attributes_for :answers, :allow_destroy => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # after sign in path override from devise
  def after_sign_in_path_for(resource)
    if resource.is_a?(AdminUser)
      admin_dashboard_path
    else
      candidate_profile_path
    end
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  skip_before_filter :verify_authenticity_token,only: [:answer]

  def index
   @exams = current_candidate.exams.present? ? current_candidate.exams : []
  end

  def show
    @exam = Exam.find_by_id(params[:id])
    model_test = @exam.exam_given(current_candidate)
    if model_test.present?
      p "<<<<<<<<<<<<<<<<<<<<,"
      p "here"
      p "<<<<<<<<<<<<<<<<<<<<,"
     @model_test = model_test
      @flag = true
    else
      @model_test = current_candidate.model_tests.create(exam_id: @exam.id)
    end
  end

  def start_exam
    @exam = Exam.find_by_id(params[:id])
    model_test = @exam.exam_given(current_candidate)
    if model_test.present?
      if model_test.is_complete?
        @flag = true
      else
        @model_test = model_test
        @flag = false
      end
    end
  end

  def answer
    model_test = ModelTest.find_by_id(params[:test_id])
    question = Question.find_by_id(params[:question_id])
    model_test_answer = model_test.model_test_answers.find_or_initialize_by(question_id: params[:question_id])
    model_test_answer.answer_id = params[:answer]
    model_test_answer.save
  end

  def complete_test
    count_marks = 0
    model_test = ModelTest.find_by_id(params[:test_id])
    model_test.model_test_answers.each do |test_answer|
      question =  Question.find_by_id(test_answer.question_id)
      if question.correct_answer_id == test_answer.answer_id
        count_marks =  count_marks + 1
      end
    end
    model_test.total_marks = count_marks
    model_test.is_complete = true
    model_test.save
    redirect_to candidate_profile_path
  end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_candidate!

  def index
  end

  def profile
    @candidate = current_candidate
  end

  def about

  end

  def contact

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_result_all
    @list = []
    Candidate.all.each do |can|
      @list << {
          :email => can.email,
          :marks => can.model_tests.sum(:total_marks) +  can.other_exams_marks.sum(:point)
      }
    end
    @list = @list.sort{|a,b| b[:marks] <=> a[:marks]}
    return @list
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/candidates/_total_marks.html.erb
<table>
  <thead>
  <th>Exam</th>
  <th>Marks</th>
  <th>Action</th>
  </thead>
  <tbody>
  <% @candidate.model_tests.each do |test| %>
      <tr>
        <td><%= test.exam.title  %></td>
        <td><%= test.total_marks  %></td>
        <td></td>
      </tr>
  <% end %>
  <% @candidate.other_exams_marks.each do |ot_exam_marks| %>
      <tr>
        <td><%= ot_exam_marks.other_exam.title  %></td>
        <td><%= ot_exam_marks.point  %></td>
        <td></td>
      </tr>
  <% end %>
  </tbody>
  <tfoot>
  <tr>
    <td><span style="text-align: right;"><b>Total</b></span></td>
    <td><b><%= @candidate.model_tests.sum(:total_marks) +  @candidate.other_exams_marks.sum(:point) %></b></td>
    <td></td>
  </tr>
  </tfoot>
</table>

app/views/admin/other_exams_marks/_form.html.erb
<% if @other_exams_mark.new_record? %>
    <%= form_tag addition_admin_other_exams_marks_path, method: :post do |f| %>
        <table>
          <tbody>
          <% OtherExam.all.each_with_index do |exam, index| %>
              <tr>
                <td>
                  <%= label_tag exam.title %>
                </td>
                <td>
                  <%= text_field_tag "exam_mark_attributes[#{index}][#{:point}]", exam.get_mark(params[:candidate_id]) %>
                </td>
                <td>
                  <%= hidden_field_tag "exam_mark_attributes[#{index}][candidate_id]", params[:candidate_id] %>
                </td>
                <td>
                  <%= hidden_field_tag "exam_mark_attributes[#{index}][other_exam_id]", exam.id %>
                </td>
              </tr>
          <% end %>
          <tr>
            <td></td>
            <td><%= submit_tag 'Save Marks' %></td>
            <td></td>
            <td></td>
          </tr>
          </tbody>
        </table>
    <% end %>
<% else %>
    <%= form_for @other_exams_mark, url: admin_other_exams_mark_path(@other_exams_mark), method: :put do |f| %>
        <table>
          <tbody>
          <tr>
            <td>
              <strong><%= f.label 'Candidate' %></strong>
            </td>
            <td>
              <%= @other_exams_mark.candidate.email %>
              <%= f.hidden_field :candidate_id %>
            </td>
          </tr>
          <tr>
            <td>
              <strong><%= f.label 'Exam Name' %></strong>
            </td>
            <td>
              <%= @other_exams_mark.other_exam.title %>
              <%= f.hidden_field :other_exam_id %>
            </td>
          </tr>
          <tr>
            <td>
              <strong><%= f.label :point %></strong>
            </td>
            <td>
              <%= f.text_field :point %>
            </td>
          </tr>
          <tr>
            <td></td>
            <td>
              <%= f.submit 'Update exam mark' %>
            </td>
          </tr>
          </tbody>
        </table>
    <% end %>
<% end %>

app/views/exams/index.html.erb
<%= content_for :page_header do %>
<% end %>
<div class="exam-content">
  <% if @exams.present? %>
      <ul class="exam-list col-lg-12">
        <% @exams.each do |exam| %>
                <li class="exam-item col-md-4">
                  <%= link_to exam_path(exam) do %>
                      <h3> <%= exam.title %> </h3>
                      <%= exam.description %>
                  <% end %>
                </li>
        <% end %>
      </ul>
    <% else %>
  <p>No Exam Assigned to you</p>
   <% end %>
</div>

app/views/exams/show.html.erb
<%= content_for :page_header do %>
<% end %>
<% if @flag %>
    <p>You have already Complete the exam</p>
<% else %>
<% if @model_test.exam.questions.present? %>
    <div class="col-sm-12 exam-Instruction">
      <li class="question-box">
        <div class="questions">
          <i class="fa fa-info-circle"> </i>
          <span>Exam Instruction </span>
        </div>
        <ul class="answer-list">
            <div class="col-sm-6">
              <div class="col-sm-6">
                Exam : <%= @exam.title %>
              </div>
              <div class="col-sm-6">
                <table class="table  borderless">
                  <tr>
                    <td>Total Question</td>
                    <td><%= @model_test.exam.questions.count  %></td>
                  </tr>
                  <tr>
                    <td>Total Marks</td>
                    <td><%= @model_test.exam.questions.count * 1 %></td>
                  </tr>
                  <tr>
                    <td>Total Time</td>
                    <td>30 minutes</td>
                  </tr>
                </table>
              </div>
            </div>
          <div class="col-sm-6">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
          </div>
        </ul>
      </li>
      <div class="col-sm-12 "><%= link_to 'Start Exam',  start_exam_exam_path(@exam), class: 'btn btn-success start-exam pull-right', remote: true %></div>
    </div>
    <div class="col-sm-12 question-list">
      <ul>
        <% @exam.questions.each do |question| %>
            <li class="question-box">
              <div class="questions">
                <i class="fa fa-question-circle"> </i>
                <span> <%= question.title %> </span>
              </div>
              <ul class="answer-list">
                <% question.answers.each do |answer| %>
                    <li>
                      <label for="answer_<%= answer.id %>">
                        <input type="radio" class="my-answer" data-q-id="<%= question.id %>" id="answer_<%= answer.id %>" value="<%= answer.id %>" name="answer_<%= question.id %>">
                        <%= answer.title %>
                      </label>
                    </li>
                <% end %>
              </ul>
            </li>
        <% end %>
      </ul>

      <div class="actions pull-right form-group">
        <%= link_to 'Submit Answer', complete_test_path(@model_test), class: 'btn btn-success',  method: :post %>
      </div>
    </div>
<% end %>
<% end %>




<script type="text/javascript">
    $(function () {
        $('.my-answer').click(function () {
            var element = $(this);
            $.ajax({
                url: "<%= test_answer_path(@model_test.id) %>",
                type: 'post',
                data: {question_id: element.attr('data-q-id'), answer: element.val()},
                success: function() {
                    alert('Go for next');
                }
            })
        });

    })


</script>

app/views/exams/start_exam.js.erb
<%# if @flag  %>
//alert('You have already attend this exam')
<%# else %>
$('.question-list').show();
$('.exam-Instruction').hide();
<%# end %>

app/views/home/about.html.erb
About Page

app/views/home/contact.html.erb
Contact Page

app/views/home/index.html.erb
<h1 style="font-size: 50px;">ISSB</h1>

app/views/home/profile.html.erb
<div>
  <h1> <%= current_candidate.email %> </h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Issb</title>
  <link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/nav_bar' %>
<div class="exam-header common-header">
  <%= yield :page_header %>
</div>
<p><%= notice %></p>
<%= yield %>

</body>
</html>

app/views/shared/_nav_bar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top"> Issb </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= render 'shared/user_profile_menu' %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a class="page-scroll" href="/"> Home </a>
        </li>
        <li>
          <a class="page-scroll" href="/exams"> Exam List </a>
        </li>
        <li>
          <a class="page-scroll" href="/about"> About </a>
        </li>
        <li>
          <a class="page-scroll" href="/contact"> Contact </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_user_profile_menu.html.erb
<% if current_candidate.present? %>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_candidate.email %>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to candidate_profile_path do %>
                <i class="fa fa-user"> </i> Profile
            <% end %>
          </li>
          <li>
            <%= link_to '#' do %>
                <i class="fa fa-archive"></i> Achivements
            <% end %>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-cog"></i> Settings
            </a>
          </li>
          <li role="separator" class="divider"></li>
          <li>
            <%= link_to destroy_candidate_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i> Logout
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
<% else %>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to 'Signup', new_candidate_registration_path %>
      </li>
      <li>
        <%= link_to 'Login', new_candidate_session_path %>
      </li>
    </ul>
<% end %>